server:
  port: 8761                #指定该Eureka实例的端口

spring:
  application:
    name: eureka-server     #服务名称,自定义

eureka:
  instance:
    hostname: 106.15.73.226
  client:
    registerWithEureka: false     #禁止注册自身
    fetchRegistry: false          #因为该服务没有注册到其他注册中心，所以关闭从注册中心拉取服务列表。
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    renewalPercentThreshold: 0.49    #设置心跳正常的阀值，默认为1，测试时可以调低
