# User Account and Authentication
server:
  port: 8041

spring:
   application:
    name: system-provider						#微服务名，唯一标识一个服务
   main:
     allow-bean-definition-overriding: true
   http:
     encoding:
       enabled: true
       charset: utf-8
       force: true
   datasource:
     type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
     profile: dev
     driver-class-name: com.mysql.jdbc.Driver                # mysql驱动包
     url: jdbc:mysql://jiafei1.wicp.vip:56695/kitchen_management?useUnicode=true&characterEncoding=utf8&useSSL=false                   # 数据库名称
     username: root
     password: 123456
     dbcp2:
       min-idle: 5                                           # 数据库连接池的最小维持连接数
       initial-size: 5                                       # 初始化连接数
       max-total: 5                                          # 最大连接数
       max-wait-millis: 86400                                # 默认值200太小 等待连接获取的最大超时时间

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  mapper-locations: classpath*:mybatis/mapper/**.xml
  type-aliases-package: cn.gxhunter.tourism.common.entity

eureka: 
  instance:
    instance-id: system-8041			 		     	#服务实例id，在eureka服务列表中Status处显示。微服务负载均衡的多个实例以此区分
    prefer-ip-address: true      							#访问路径可以显示IP地址

info: 
  app.name: system-provider
  company.name: www.gxhunter.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$