spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
eureka:
  profiles: dev		#开发环境
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: test
eureka:
  profiles: test   #测试环境
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://54.223.237.60:8761/eureka/




