spring: 
  profiles: 
    active: 
    - dev
---    
spring: 
 profiles: dev
 datasource:
   type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
   driver-class-name: com.mysql.jdbc.Driver                # mysql驱动包
   url: jdbc:mysql://localhost:3306/tourism_v2?useUnicode=true&characterEncoding=utf8
   username: devops
   password: gclv2020
   dbcp2:
     min-idle: 5                                           # 数据库连接池的最小维持连接数
     initial-size: 5                                       # 初始化连接数
     max-total: 5                                          # 最大连接数
     max-wait-millis: 86400                                # 默认值200太小 等待连接获取的最大超时时间
    
mybatis:
  profiles: dev
  config-location: classpath:mybatis/mybatis.cfg.xml         # mybatis配置文件所在路径
  type-aliases-package: cn.gxhunter.tourism.common.entity    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                        # mapper映射文件
  
---
spring: 
 profiles: test
 datasource:  
   type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
   driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
   url: jdbc:mysql://127.0.0.1:3306/tourism_v2?useUnicode=true&characterEncoding=utf8&useSSL=false			       # 数据库名称
   username: devops
   password: gclv2020
   dbcp2: 
    min-idle: 5                                           # 数据库连接池的最小维持连接数
    initial-size: 5                                       # 初始化连接数
    max-total: 5                                          # 最大连接数
    max-wait-millis: 2000                                  # 等待连接获取的最大超时时间
    
mybatis:
  profiles: test
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: cn.gxhunter.tourism.common.entity	# 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml      					# mapper映射文件
 